style_edition = "2021"

max_width=100
use_small_heuristics="Max"
newline_style="Unix"

reorder_imports = true

# Once these stabilize, they'd be nice
# indent_style="Visual"
# fn_single_line=true
# fn_params_layout="Compressed"
# comment_width=100
# overflow_delimited_expr=true
# imports_granularity="Module"
