[workspace]
members = [
    "imageflow_helpers",
    "imageflow_http_helpers",
    "imageflow_types",
    "imageflow_riapi",
    "imageflow_core",
    "imageflow_abi",
    "imageflow",
    "imageflow_tool",
    "c_components",
#    "c_components/tests",
]
resolver = "2"

[profile.release]
debug = true

# RIAPI Tests take 600ms each at 0, 200ms each at 1, 36ms each at 2, 26ms each at 3
[profile.test]
opt-level = 2

[patch.crates-io]
libwebp-sys = { git = "https://github.com/lilith/libwebp-sys" }


#bennch with cpu native
[profile.bench]
opt-level = 3
lto = "fat"
codegen-units = 1
panic = "abort"

# [build]
# rustflags = ["-C", "target-cpu=native"]
