name: 'Setup Git for Windows ARM64'
description: 'Set up Git for Windows ARM64 environment with necessary tools'
# maybe switch to winget someday?
# Add-AppxPackage -RegisterByFamilyName -MainPackage Microsoft.DesktopAppInstaller_8wekyb3d8bbwe
runs:
  using: "composite"
  steps:

    - name: Check if Git is installed, returning step variable
      shell: powershell
      id: git-installed
      run: |
        if (Test-Path "C:\Program Files\Git\bin\git.exe") {
          Write-Host "Git is already installed"
          echo "::set-output name=git-installed::true"
        } else {
          Write-Host "Git is not installed"
          echo "::set-output name=git-installed::false"
        }


    - name: Install Git
      shell: powershell
      run: |
        $url = "https://github.com/git-for-windows/git/releases/download/v2.47.1.windows.2/Git-2.47.1.2-arm64.exe"
        Invoke-WebRequest -Uri $url -OutFile git-installer.exe
        Start-Process -FilePath .\git-installer.exe -ArgumentList "/VERYSILENT", "/NORESTART" -Wait
      if: steps.git-installed.outputs.git-installed == 'false'


    - name: Add Git and GNU tools (required for actions/cache to work (tar is needed)) to PATH
      shell: powershell
      run: |
        echo "C:\Program Files\Git\usr\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
        echo "C:\Program Files\Git\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

