name: Windows on ARM64 Test

on:
  push:
    branches:
      - '*'
  pull_request:
  # Allow manual triggers
  workflow_dispatch:

jobs:
  test_win_arm64:
    runs-on: windows-11-arm-32gb

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Windows ARM64
        uses: ./.github/actions/setup-win-arm64

      - name: Checkout code again with git, so git commands work.
        uses: actions/checkout@v4

      - name: Install NASM
        uses: ./.github/actions/install-nasm

      - name: Test Build
        run: "& Launch-VsDevShell.ps1 | cargo test --all"
        env:
          RUSTFLAGS: -C target-cpu=generic


  # You can add more experimental jobs here in the future
  # test_another_experimental:
  #   runs-on: ...
  #   steps:
  #     ...
