name: Windows on ARM64 Test

on:
  push:
    branches:
      - '*'
  pull_request:
  # Allow manual triggers
  workflow_dispatch:

jobs:
  test_win_arm64:
    if: false
    runs-on: windows-11-arm-32gb

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Windows ARM64
        uses: ./.github/actions/setup-win-arm64

      - name: Checkout code again with git, so git commands work.
        uses: actions/checkout@v4

      - name: Test
        run: "& Launch-VsDevShell.ps1 | cargo test --all --release --target=aarch64-pc-windows-msvc"
        env:
          RUSTFLAGS: -Ctarget-cpu=generic

      - name: Build
        run: "& Launch-VsDevShell.ps1 | cargo build --all --release --target=aarch64-pc-windows-msvc"
        env:
          RUSTFLAGS: -Ctarget-cpu=generic


  # You can add more experimental jobs here in the future
  # test_another_experimental:
  #   runs-on: ...
  #   steps:
  #     ...
